service: taco-gallery

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-2
  stage: dev
  environment:
    TESTNUM: 27
    TESTSTR: hello
    AUTH0_DOMAIN: pfernandom.auth0.com
    AUTH0_CLIENTID: L7YiTnpuzmfa1W9spj7fIpwXgHKzSmNX

resources:
  Resources:
    TacosDB:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: name
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: TacoGallery

functions:
  authorizerFunc:
      handler: handler.auth
  helloPublic:
    handler: handler.hello
    events:
      - http:
          path: helloPublic
          method: get
          cors: true
  helloIAM:
      handler: handler.hello
      events:
        - http:
            path: helloIAM
            method: get
            cors: true
            authorizer: authorizerFunc
  helloAuth0:
      handler: handler.hello
      events:
        - http:
            path: helloAuth0
            method: get
            cors: true
            authorizer: authorizerFunc
  getTaco:
    handler: handler.getTaco
    events:
      - http:
          path: taco/{id}
          method: get
          authorizer: authorizerFunc
  saveTaco:
    handler: handler.saveTaco
    events:
      - http:
          path: taco
          method: post
          authorizer: authorizerFunc


plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-webpack

custom:
  webpackIncludeModules:
    packagePath: './package.json'
  dynamodb:
      start:
        migrate: true
  serverless-offline:
    babelOptions:
      presets: ["es2015", "stage-2"]